/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.segregator;

import edu.neu.wasteManagement.ui.collector.*;
import edu.neu.wasteManagement.ui.cordinator.*;
import edu.neu.wasteManagement.ui.common.UserTrashJPanel;
import edu.neu.wasteManagement.ui.common.UserProfileJPanel;
import edu.neu.wasteManagement.ui.common.ManageWasteRequestsJPanel;
import edu.neu.wasteManagement.ui.common.GarbageCollectRequestJPanel;
import edu.neu.wasteManagement.ui.principal.*;
import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.workQueue.WorkRequestType;
import edu.neu.wasteManagement.ui.BaseJPanel;
import edu.neu.wasteManagement.utility.Utility;
import static edu.neu.wasteManagement.utility.Utility.imageResize;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author ingale.r
 */
public class WasteSegregatorWorkArea extends BaseJPanel {

    public WasteSegregatorWorkArea(Ecosystem system) {
        super(system);
        initComponents();
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePic = new javax.swing.JLabel();
        lblGreetings = new javax.swing.JLabel();
        lblWasteRequest = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblProfilePic.setPreferredSize(new java.awt.Dimension(255, 255));

        lblGreetings.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblGreetings.setText("Hello !");

        lblWasteRequest.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblWasteRequest.setForeground(new java.awt.Color(0, 153, 255));
        lblWasteRequest.setText("Manage Waste Requests > ");
        lblWasteRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWasteRequestMouseClicked(evt);
            }
        });

        lblProfile.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(0, 153, 255));
        lblProfile.setText("My Profile >");
        lblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfileMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        jLabel1.setText("Name : ");

        jLabel3.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        jLabel3.setText("Email id: ");

        lblName.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblName.setText("jLabel4");

        lblEmail.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblEmail.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(lblGreetings))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProfile)
                                    .addComponent(lblWasteRequest))))
                        .addGap(504, 504, 504)))
                .addContainerGap(12632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblGreetings))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(lblWasteRequest)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName)
                    .addComponent(lblProfile))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblEmail))
                .addContainerGap(936, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblWasteRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWasteRequestMouseClicked
        //Mouse Click
       Utility.switchPanel(new ManageWasteRequestsJPanel(system), system.getWorkArea());     
    }//GEN-LAST:event_lblWasteRequestMouseClicked

    private void lblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfileMouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new UserProfileJPanel(system), system.getWorkArea());
    }//GEN-LAST:event_lblProfileMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblWasteRequest;
    // End of variables declaration//GEN-END:variables

    private void initialSetup() {
        // Adjust icon resolution
        
//      imageResize(lblProfilePic, "./src/edusera/assets/edusera-user-stock-profile-pic.png");
   

    }    
}
