/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.integrator;

import edu.neu.wasteManagement.ui.common.*;
import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.products.Product;
import edu.neu.wasteManagement.business.workQueue.UserWasteCollectionRequest;
import edu.neu.wasteManagement.business.workQueue.Waste;
import edu.neu.wasteManagement.business.workQueue.WasteProcessingRequest;
import edu.neu.wasteManagement.business.workQueue.WorkRequest;
import edu.neu.wasteManagement.business.workQueue.WorkRequestType;
import edu.neu.wasteManagement.ui.BaseJPanel;
import edu.neu.wasteManagement.utility.Utility;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ingale.r
 */
public class WasteConvertJPanel extends BaseJPanel {

    /**
     * Creates new form CreateCourseJPanel
     */

    private List<Waste> wastes;
    private List<Product> products;
    public WasteConvertJPanel(Ecosystem system) {
        super(system);
        this.wastes = new ArrayList<>();
        this.products = new ArrayList<>();
        initComponents();
        initSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWaste = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        jLabel1.setText("Waste Conversion");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Waste Conversion");

        jLabel9.setText("Waste");

        removeButton.setText("<");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        btnAddProduct.setText(">");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnBack3.setText("Convert ?");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        tblWaste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Waste Type"
            }
        ));
        jScrollPane2.setViewportView(tblWaste);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Products"
            }
        ));
        jScrollPane3.setViewportView(tblProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnBack3)))
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnAddProduct)
                        .addGap(17, 17, 17)
                        .addComponent(removeButton)))
                .addGap(61, 61, 61)
                .addComponent(btnBack3)
                .addContainerGap(529, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
//        Product str2 = addedProducts.getSelectedValue();
//        if(addedProducts.getSelectedIndex()==-1){
//            JOptionPane.showMessageDialog(this, "No Data selected");
//        } else{
//            int value = addedProducts.getSelectedIndex();
//
//            listProductsModel.addElement(str2);
//            listProducts.setModel(listProductsModel);
//
//            if(addedProductsModel.getSize() != 0){
//                addedProductsModel.removeElementAt(value);
//            }
//        }
//        updatePrice(-str2.getTargetPrice(), -str2.getCeilingPrice(), -str2.getFloorPrice());
    }//GEN-LAST:event_removeButtonActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        
        Product p = null;
//
//        Product selectedValue = listProducts.getSelectedValue();
//
//        if (selectedValue != null) {
//
//            int countProducts = addedProductsModel.getSize();
//            if(countProducts > 1){
//                JOptionPane.showMessageDialog(this, "Only 2 Products can be added!");
//                return;
//            }
//
//            // Add the selected item to the addedProductsModel list
//            addedProductsModel.addElement(selectedValue);
//
//            // Remove the selected item from the listProductsModel list
//            listProductsModel.removeElement(selectedValue);
//
//            // Set models for both lists
//            listProducts.setModel(listProductsModel);
//            addedProducts.setModel(addedProductsModel);
//
//            updatePrice(selectedValue.getTargetPrice(),selectedValue.getFloorPrice(),selectedValue.getCeilingPrice());

//        } else {
//            JOptionPane.showMessageDialog(this, "No data selected", "Oops..", HEIGHT);
//        }

    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton removeButton;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblWaste;
    // End of variables declaration//GEN-END:variables

 
   
    private void initSetup() {
       populateWasteTable();
       populateProductTable();
    }
    
    private void populateTable(){
        
//        DefaultTableModel model = (DefaultTableModel) tblWaste.getModel(); //Convert to TableModel to defaultTableModel
//        model.setRowCount(0);
//        
//        List<Waste> wastes = null;
//        
//        if(request instanceof UserWasteCollectionRequest)
//            wastes = ((UserWasteCollectionRequest)request).getWasteToCollect();
//        else if( request instanceof WasteProcessingRequest)
//            wastes = ((WasteProcessingRequest)request).getWasteToCollect();
//        
//        for (Waste waste : wastes) {
//
//            //to create lines or row (row is small array of object with 3 members)
//            Object[] row = new Object[2];
//             row[0] = waste;
//             row[1] = waste.getAmount();
//
//            model.addRow(row);
//        }
    }   

    private void populateWasteTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblWaste.getModel(); //Convert to TableModel to defaultTableModel
        model.setRowCount(0);   
           
           for(Waste waste : wastes){
            Object[] row = new Object[1];
            row[0] = waste;

            model.addRow(row);
           }
    }

    private void populateProductTable() {
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel(); 
           model.setRowCount(0);
    }

    private void loadWaste() {
        List<Waste> recyclableWaste = system.getListOfRecyclableWasteForUser(system.getLoggedInUser());
        wastes.addAll(recyclableWaste);
    }

}


