/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.retail;

import edu.neu.wasteManagement.ui.principal.*;
import edu.neu.wasteManagement.ui.common.UserTrashJPanel;
import edu.neu.wasteManagement.ui.common.UserProfileJPanel;
import edu.neu.wasteManagement.ui.common.GarbageCollectRequestJPanel;
import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.workQueue.WorkRequestType;
import edu.neu.wasteManagement.ui.BaseJPanel;
import edu.neu.wasteManagement.ui.marketPlace.MarketPlaceHomeJPanel;
import edu.neu.wasteManagement.utility.Utility;
import static edu.neu.wasteManagement.utility.Utility.imageResize;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author prart
 */
public class RetailUserWorkArea extends BaseJPanel {

    public RetailUserWorkArea(Ecosystem system) {
        super(system);
        initComponents();
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourses = new javax.swing.JLabel();
        lblReviewProfessor = new javax.swing.JLabel();
        lblMyProfile = new javax.swing.JLabel();
        lblMyGrades = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblCourses.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblCourses.setForeground(new java.awt.Color(0, 153, 255));
        lblCourses.setText("Visit Marketplace >");
        lblCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCoursesMouseClicked(evt);
            }
        });

        lblReviewProfessor.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblReviewProfessor.setForeground(new java.awt.Color(0, 153, 255));
        lblReviewProfessor.setText("Raise Request >");
        lblReviewProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReviewProfessorMouseClicked(evt);
            }
        });

        lblMyProfile.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblMyProfile.setForeground(new java.awt.Color(0, 153, 255));
        lblMyProfile.setText("My Profile >");
        lblMyProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMyProfileMouseClicked(evt);
            }
        });

        lblMyGrades.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblMyGrades.setForeground(new java.awt.Color(0, 153, 255));
        lblMyGrades.setText("See my trash >");
        lblMyGrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMyGradesMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Retail User Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMyGrades)
                            .addComponent(lblCourses))
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMyProfile)
                            .addComponent(lblReviewProfessor))))
                .addContainerGap(13065, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourses)
                    .addComponent(lblReviewProfessor))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMyProfile)
                    .addComponent(lblMyGrades))
                .addContainerGap(1010, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCoursesMouseClicked
        //Mouse Click
       Utility.switchPanel(new MarketPlaceHomeJPanel(system), system.getWorkArea());
    }//GEN-LAST:event_lblCoursesMouseClicked

    private void lblReviewProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReviewProfessorMouseClicked
        // TODO add your handling code here:
       Utility.switchPanel(new GarbageCollectRequestJPanel(system, WorkRequestType.RETAIL_WASTE_COLLECTION_REQUEST), system.getWorkArea());
    }//GEN-LAST:event_lblReviewProfessorMouseClicked

    private void lblMyProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyProfileMouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new UserProfileJPanel(system), system.getWorkArea());
    }//GEN-LAST:event_lblMyProfileMouseClicked

    private void lblMyGradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyGradesMouseClicked
        // TODO add your handling code here:
         Utility.switchPanel(new UserTrashJPanel(system), system.getWorkArea());     

    }//GEN-LAST:event_lblMyGradesMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblMyGrades;
    private javax.swing.JLabel lblMyProfile;
    private javax.swing.JLabel lblReviewProfessor;
    // End of variables declaration//GEN-END:variables

    private void initialSetup() {
        // Adjust icon resolution
        
//      imageResize(lblProfilePic, "./src/edusera/assets/edusera-user-stock-profile-pic.png");
   

    }    
}
