/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.admin;

import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.Ecosystem.OrganizationEnterprise;
import edu.neu.wasteManagement.business.enterprise.Enterprise;
import edu.neu.wasteManagement.business.organization.Organization;
import edu.neu.wasteManagement.ui.BaseJPanel;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author chinmaygulhane
 */
public class ManageOrganizationJPanel extends BaseJPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(Ecosystem system) {
        super(system);
                System.out.println("In manage Org");
        initComponents();
        populateTypeComboBox();
        populateOrgTable();
    }
    
 
    private void populateOrgTable() {
        DefaultTableModel model = (DefaultTableModel) OrgTbl.getModel();
        JTableHeader header = OrgTbl.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 14));
        model.setRowCount(0);
        System.out.println(system.getEnterpriseDir().getEnterpriseList());
        System.out.println(system.getEnterpriseDir().getEnterpriseList());
        for (OrganizationEnterprise obj : system.fetchOrganizationForTable()) {
            System.out.println("org name"+ obj.org.getName());
            System.out.println("ent name"+obj.ent.getName());
            Object[] row = new Object[4];
            row[0] = obj.org;
            row[1] = obj.org.getName();
            row[2] = obj.ent.getName();
            model.addRow(row);
        }
    }
    
    
    public void populateTypeComboBox() {
        
//    REGIONAL_WASTE_MANAGEMENT_ORG,
//    MUNICIPAL_WASTE_PROCESSING_ORG,
//    REUSABLE_MATERIALS_MANAGEMENT_ORG,
//    RETAIL_WASTE_PROCESSING_ORG,
//    PRODUCT_CONVERSION_ORG,
//    MARKETPLACE_ORG
        orgTypeComboBox.addItem("Regional Waste Managemnt");
        orgTypeComboBox.addItem("Municipal Waste Management");
        orgTypeComboBox.addItem("Reusable Materials Management");
        orgTypeComboBox.addItem("Retail Waste Processing");
        orgTypeComboBox.addItem("Product Conversion");
        orgTypeComboBox.addItem("Marketplace");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdateOrg = new javax.swing.JButton();
        btnCancelOrg = new javax.swing.JButton();
        btnSaveOrg = new javax.swing.JButton();
        btnViewOrg = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        btnDeleteOrg = new javax.swing.JButton();
        txtPerName = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        orgTypeComboBox = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        OrgTbl = new javax.swing.JTable();
        lblName2 = new javax.swing.JLabel();
        entrpiseComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        btnUpdateOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdateOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateOrg.setText("Update");
        btnUpdateOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrgActionPerformed(evt);
            }
        });

        btnCancelOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancelOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelOrg.setText("Cancel");
        btnCancelOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrgActionPerformed(evt);
            }
        });

        btnSaveOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSaveOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveOrg.setText("Save");
        btnSaveOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveOrgActionPerformed(evt);
            }
        });

        btnViewOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnViewOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrg.setText("View Organization");
        btnViewOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrgActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Manage Organization");

        btnDeleteOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteOrg.setText("Delete");
        btnDeleteOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrgActionPerformed(evt);
            }
        });

        lblName1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName1.setText("Name:");

        lblGender.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Type:");

        orgTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgTypeComboBoxActionPerformed(evt);
            }
        });

        OrgTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Type", "Enterprise"
            }
        ));
        jScrollPane7.setViewportView(OrgTbl);

        lblName2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblName2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName2.setText("Enterprise:");

        entrpiseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrpiseComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblName1))
                            .addComponent(lblName2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveOrg)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateOrg)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelOrg))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(entrpiseComboBox, 0, 250, Short.MAX_VALUE)
                                    .addComponent(orgTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPerName))
                                .addGap(123, 123, 123)
                                .addComponent(btnViewOrg)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteOrg)))
                        .addGap(24, 24, 24)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel73)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDeleteOrg)
                                .addComponent(btnViewOrg))
                            .addComponent(txtPerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entrpiseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orgTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender)))
                    .addComponent(lblName1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveOrg)
                    .addComponent(btnUpdateOrg)
                    .addComponent(btnCancelOrg))
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrgActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = OrgTbl.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }

        //        // Validation if any field is left empty
        //        if (txtUserNuId.getText().isEmpty() || txtUserPassword.getText().isEmpty() || txtUserName.getText().isEmpty() || !(jRadioButtonEnabledStatusNo.isSelected() || jRadioButtonEnabledStatusYes.isSelected())) {
            //            JOptionPane.showMessageDialog(null, "Please enter all the fields");
            //            return;
            //        }
        //
        //        DefaultTableModel model = (DefaultTableModel) UserTbl.getModel();
        //        User user = (User) model.getValueAt(selectedRowIndex, 0);
        //
        //        String nuId = txtUserNuId.getText();
        //        String userName = txtUserName.getText();
        //        String password = txtUserPassword.getText();
        //        String isActive = "No";
        //        if (jRadioButtonEnabledStatusYes.isSelected()) {
            //            isActive = "Yes";
            //        }
        //        boolean isPassWordValid = user.isPasswordValid(password);
        //        if (!isPassWordValid) {
            //            JOptionPane.showMessageDialog(null, "New password cannot be a previously used password. Please try again");
            //            return;
            //        }
        //        user.setUserName(userName);
        //        user.setPassword(password);
        //        user.setEnabledStaus(isActive);
        //        user.setNUID(nuId);
        //
        //        populateUserTable();
        //        clearUserDetails();
        JOptionPane.showMessageDialog(this, "User Information Updated");
    }//GEN-LAST:event_btnUpdateOrgActionPerformed

    private void btnCancelOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrgActionPerformed
        // TODO add your handling code here:
        //        clearUserDetails();
    }//GEN-LAST:event_btnCancelOrgActionPerformed

    private void btnSaveOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveOrgActionPerformed
        // TODO add your handling code here:
        // Validation if any field is left empty

        JOptionPane.showMessageDialog(this, "User Information Saved");
    }//GEN-LAST:event_btnSaveOrgActionPerformed

    private void btnViewOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrgActionPerformed
        // TODO add your handling code here:
        btnUpdateOrg.setEnabled(true);
        btnSaveOrg.setEnabled(false);
        //        txtUserNuId.setEnabled(false);
        //
        //        int selectedRowIndex = UserTbl.getSelectedRow();
        //        if (selectedRowIndex < 0) {
            //            JOptionPane.showMessageDialog(this, "Please Select a Row to View.");
            //            return;
            //        }
        //
        //        DefaultTableModel model = (DefaultTableModel) UserTbl.getModel();
        //        User selectedUserDetails = (User) model.getValueAt(selectedRowIndex, 0);
        //
        //        txtUserNuId.setText(selectedUserDetails.getNUID());
        //        txtUserName.setText(selectedUserDetails.getUserName());
        //        txtUserPassword.setText(selectedUserDetails.getPassword());
        //        if (selectedUserDetails.getEnabledStaus() == "Yes") {
            //            jRadioButtonEnabledStatusYes.setSelected(true);
            //        } else {
            //            jRadioButtonEnabledStatusNo.setSelected(true);
            //        }
    }//GEN-LAST:event_btnViewOrgActionPerformed

    private void btnDeleteOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteOrgActionPerformed

    private void orgTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgTypeComboBoxActionPerformed

    private void entrpiseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrpiseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrpiseComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrgTbl;
    private javax.swing.JButton btnCancelOrg;
    private javax.swing.JButton btnDeleteOrg;
    private javax.swing.JButton btnSaveOrg;
    private javax.swing.JButton btnUpdateOrg;
    private javax.swing.JButton btnViewOrg;
    private javax.swing.JComboBox<String> entrpiseComboBox;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JComboBox<String> orgTypeComboBox;
    private javax.swing.JTextField txtPerName;
    // End of variables declaration//GEN-END:variables
}
