/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.admin;

import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.enterprise.Enterprise;
import edu.neu.wasteManagement.business.enterprise.EnterpriseType;
import edu.neu.wasteManagement.business.organization.Organization;
import edu.neu.wasteManagement.business.organization.Type;
import edu.neu.wasteManagement.ui.BaseJPanel;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author chinmaygulhane
 */
public class ManageEnterpriseJPanel extends BaseJPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageEnterpriseJPanel(Ecosystem system) {
        super(system);
                System.out.println("In manage Enterprise");
        initComponents();
        populateTypeComboBox();
        populateOrgTable();
    }
    
    
    public void populateTypeComboBox() {
        for (EnterpriseType type : EnterpriseType.values()) {
            entTypeComboBox.addItem(convertToDisplayName(type));
        }
    }
    
 
    private void populateOrgTable() {
        DefaultTableModel model = (DefaultTableModel) EntTbl.getModel();
        JTableHeader header = EntTbl.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 14));
        model.setRowCount(0);
        System.out.println(system.getAllEnterprises());
        for (Enterprise ent : system.getAllEnterprises()) {
            System.out.println("ent.getType()"+ent.getEnterpriseType());
            System.out.println(ent.toString());
            Object[] row = new Object[4];
            row[0] = ent;
            row[1] = convertToDisplayName(ent.getEnterpriseType());
            model.addRow(row);
        }
    }
    
    public String convertToDisplayName(EnterpriseType enterpriseType) {
        switch (enterpriseType) {
            case WASTE_MANAGEMENT_CORP:
                return "Waste Management Corporation";
            case MUNICIPAL_WASTE_SERVICES:
                return "Municipal Waste Services";
            case RETAIL_WASTE_ENTERPRISE:
                return "Retail Waste Enterprise";
            case GREEN_LIVING_SOLUTIONS:
                return "Green Living Solutions";
            default:
                // Handle the default case or throw an exception if needed
                throw new IllegalArgumentException("Invalid enterprise type");
        }
    }
    
    public static EnterpriseType getEnterpriseType(String enterpriseTypeName) {
        switch (enterpriseTypeName) {
            case "Waste Management Corporation":
                return EnterpriseType.WASTE_MANAGEMENT_CORP;
            case "Municipal Waste Services":
                return EnterpriseType.MUNICIPAL_WASTE_SERVICES;
            case "Retail Waste Enterprise":
                return EnterpriseType.RETAIL_WASTE_ENTERPRISE;
            case "Green Living Solutions":
                return EnterpriseType.GREEN_LIVING_SOLUTIONS;
            default:
                // Handle the case when the input doesn't match any of the known types
                return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel73 = new javax.swing.JLabel();
        txtEntName = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        entTypeComboBox = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        EntTbl = new javax.swing.JTable();
        btnUpdateEnt = new javax.swing.JButton();
        btnCancelEnt = new javax.swing.JButton();
        btnSaveEnt = new javax.swing.JButton();
        btnViewEnt = new javax.swing.JButton();
        btnDeleteEnt = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Manage Enterprise");

        lblName1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName1.setText("Name:");

        lblType.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblType.setText("Type:");

        entTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entTypeComboBoxActionPerformed(evt);
            }
        });

        EntTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Type"
            }
        ));
        jScrollPane7.setViewportView(EntTbl);

        btnUpdateEnt.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateEnt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdateEnt.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateEnt.setText("Update");
        btnUpdateEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEntActionPerformed(evt);
            }
        });

        btnCancelEnt.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelEnt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancelEnt.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelEnt.setText("Cancel");
        btnCancelEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEntActionPerformed(evt);
            }
        });

        btnSaveEnt.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveEnt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSaveEnt.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveEnt.setText("Save");
        btnSaveEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEntActionPerformed(evt);
            }
        });

        btnViewEnt.setBackground(new java.awt.Color(0, 0, 0));
        btnViewEnt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewEnt.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEnt.setText("View Enterprise");
        btnViewEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEntActionPerformed(evt);
            }
        });

        btnDeleteEnt.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteEnt.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteEnt.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEnt.setText("Delete");
        btnDeleteEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSaveEnt)
                            .addGap(18, 18, 18)
                            .addComponent(btnUpdateEnt)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelEnt))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblName1)
                                .addComponent(lblType))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEntName)
                                .addComponent(entTypeComboBox, 0, 250, Short.MAX_VALUE))
                            .addGap(147, 147, 147)
                            .addComponent(btnViewEnt)
                            .addGap(18, 18, 18)
                            .addComponent(btnDeleteEnt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel73)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeleteEnt)
                        .addComponent(btnViewEnt))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName1)
                        .addComponent(txtEntName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEnt)
                    .addComponent(btnUpdateEnt)
                    .addComponent(btnCancelEnt))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entTypeComboBoxActionPerformed

    private void btnUpdateEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEntActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = EntTbl.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }

//        // Validation if any field is left empty
//        if (txtUserNuId.getText().isEmpty() || txtUserPassword.getText().isEmpty() || txtUserName.getText().isEmpty() || !(jRadioButtonEnabledStatusNo.isSelected() || jRadioButtonEnabledStatusYes.isSelected())) {
//            JOptionPane.showMessageDialog(null, "Please enter all the fields");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) EntTbl.getModel();
//        User user = (User) model.getValueAt(selectedRowIndex, 0);
//
//        String nuId = txtUserNuId.getText();
//        String userName = txtUserName.getText();
//        String password = txtUserPassword.getText();
//        String isActive = "No";
//        if (jRadioButtonEnabledStatusYes.isSelected()) {
//            isActive = "Yes";
//        }
//        boolean isPassWordValid = user.isPasswordValid(password);
//        if (!isPassWordValid) {
//            JOptionPane.showMessageDialog(null, "New password cannot be a previously used password. Please try again");
//            return;
//        }
//        user.setUserName(userName);
//        user.setPassword(password);
//        user.setEnabledStaus(isActive);
//        user.setNUID(nuId);
//
//        populateUserTable();
//        clearUserDetails();
        JOptionPane.showMessageDialog(this, "User Information Updated");
    }//GEN-LAST:event_btnUpdateEntActionPerformed

    private void btnCancelEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEntActionPerformed
        // TODO add your handling code here:
//        clearUserDetails();
    }//GEN-LAST:event_btnCancelEntActionPerformed

    private void btnSaveEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEntActionPerformed
        // TODO add your handling code here:
        // Validation if any field is left empty
        String entName = txtEntName.getText();
        EnterpriseType entType = getEnterpriseType((String) entTypeComboBox.getSelectedItem());
        System.out.println("entName"+ entName);
        System.out.println(entTypeComboBox.getSelectedItem());
        System.out.println(getEnterpriseType((String) entTypeComboBox.getSelectedItem()));
        system.getEnterpriseDir().createAndAddEnterprise(entName, entType);
        
        JOptionPane.showMessageDialog(this, "Enterprise Information Saved");
    }//GEN-LAST:event_btnSaveEntActionPerformed

    private void btnViewEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEntActionPerformed
        // TODO add your handling code here:
        btnUpdateEnt.setEnabled(true);
        btnSaveEnt.setEnabled(false);
        
        int selectedRowIndex = EntTbl.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a Row to View.");
            return;
        }
//
        DefaultTableModel model = (DefaultTableModel) EntTbl.getModel();
        Enterprise selectedEnterpriseDetails = (Enterprise) model.getValueAt(selectedRowIndex, 0);
//
//        txtUserNuId.setText(selectedUserDetails.getNUID());
//        txtUserName.setText(selectedUserDetails.getUserName());
//        txtUserPassword.setText(selectedUserDetails.getPassword());
//        if (selectedUserDetails.getEnabledStaus() == "Yes") {
//            jRadioButtonEnabledStatusYes.setSelected(true);
//        } else {
//            jRadioButtonEnabledStatusNo.setSelected(true);
//        }
    }//GEN-LAST:event_btnViewEntActionPerformed

    private void btnDeleteEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteEntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EntTbl;
    private javax.swing.JButton btnCancelEnt;
    private javax.swing.JButton btnDeleteEnt;
    private javax.swing.JButton btnSaveEnt;
    private javax.swing.JButton btnUpdateEnt;
    private javax.swing.JButton btnViewEnt;
    private javax.swing.JComboBox<String> entTypeComboBox;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtEntName;
    // End of variables declaration//GEN-END:variables
}
