/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.admin;

import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.Ecosystem.OrganizationEnterprise;
import edu.neu.wasteManagement.business.enterprise.Enterprise;
import edu.neu.wasteManagement.business.enterprise.EnterpriseType;
import edu.neu.wasteManagement.business.organization.Organization;
import edu.neu.wasteManagement.business.organization.Type;
import edu.neu.wasteManagement.ui.BaseJPanel;
import static edu.neu.wasteManagement.ui.admin.ManageEnterpriseJPanel.getEnterpriseType;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author chinmaygulhane
 */
public class ManageOrganizationJPanel extends BaseJPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(Ecosystem system) {
        super(system);
        initComponents();
        populateTypeComboBox();
        populateEnterpriseComboBox();
        populateOrgTable();
        btnUpdateOrg.setEnabled(false);
    }
    
 
    private void populateOrgTable() {
        DefaultTableModel model = (DefaultTableModel) OrgTbl.getModel();
        JTableHeader header = OrgTbl.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 14));
        model.setRowCount(0);
        for (OrganizationEnterprise obj : system.fetchOrganizationForTable()) {
            System.out.println("org name"+ obj.org.getName());
            System.out.println("ent name"+obj.ent.getName());
            Object[] row = new Object[4];
            row[0] = obj.org;
            row[1] = convertOrganizationToDisplayName(obj.org.getType());
            row[2] = obj.ent;
            model.addRow(row);
        }
    }
    
    
    public void populateTypeComboBox() {
        for (Type type : Type.values()) {
            orgTypeComboBox.addItem(convertOrganizationToDisplayName(type));
        }        
    }
    
    public void populateEnterpriseComboBox() {
        for (Enterprise ent : system.getAllEnterprises()) {
            entrpiseComboBox.addItem(ent.getName());
        }  
    }
    
    public void clearOrgFields() {
        txtOrgName.setText("");
        btnSaveOrg.setEnabled(true);
        btnUpdateOrg.setEnabled(false);
    }
    
    public String convertOrganizationToDisplayName(Type orgType) {
        switch (orgType) {
            case REGIONAL_WASTE_MANAGEMENT_ORG:
                return "Regional Waste Management Organization";
            case MUNICIPAL_WASTE_PROCESSING_ORG:
                return "Municipal Waste Processing Organization";
            case REUSABLE_MATERIALS_MANAGEMENT_ORG:
                return "Reusable Materials Management Organization";
            case RETAIL_WASTE_PROCESSING_ORG:
                return "Retail Waste Processing Organization";
            case PRODUCT_CONVERSION_ORG:
                return "Product Conversion Organization";
            case MARKETPLACE_ORG:
                return "Marketplace Organization";
            default:
                // Handle the default case or throw an exception if needed
                throw new IllegalArgumentException("Invalid enterprise type");
        }
    }

    public static Type getOrganizationType(String orgTypeName) {
        switch (orgTypeName) {
            case "Regional Waste Management Organization":
                return Type.REGIONAL_WASTE_MANAGEMENT_ORG;
            case "Municipal Waste Processing Organization":
                return Type.MUNICIPAL_WASTE_PROCESSING_ORG;
            case "Reusable Materials Management Organization":
                return Type.REUSABLE_MATERIALS_MANAGEMENT_ORG;
            case "Retail Waste Processing Organization":
                return Type.RETAIL_WASTE_PROCESSING_ORG;
            case "Product Conversion Organization":
                return Type.PRODUCT_CONVERSION_ORG;
            case "Marketplace Organization":
                return Type.MARKETPLACE_ORG;
            default:
                // Handle the case when the input doesn't match any of the known types
                return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdateOrg = new javax.swing.JButton();
        btnCancelOrg = new javax.swing.JButton();
        btnSaveOrg = new javax.swing.JButton();
        btnViewOrg = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        btnDeleteOrg = new javax.swing.JButton();
        txtOrgName = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        orgTypeComboBox = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        OrgTbl = new javax.swing.JTable();
        lblName2 = new javax.swing.JLabel();
        entrpiseComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        btnUpdateOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUpdateOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateOrg.setText("Update");
        btnUpdateOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrgActionPerformed(evt);
            }
        });

        btnCancelOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancelOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelOrg.setText("Cancel");
        btnCancelOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrgActionPerformed(evt);
            }
        });

        btnSaveOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSaveOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveOrg.setText("Save");
        btnSaveOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveOrgActionPerformed(evt);
            }
        });

        btnViewOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnViewOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrg.setText("View Organization");
        btnViewOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrgActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Manage Organization");

        btnDeleteOrg.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDeleteOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteOrg.setText("Delete");
        btnDeleteOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrgActionPerformed(evt);
            }
        });

        lblName1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName1.setText("Name:");

        lblGender.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Type:");

        orgTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgTypeComboBoxActionPerformed(evt);
            }
        });

        OrgTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Type", "Enterprise"
            }
        ));
        jScrollPane7.setViewportView(OrgTbl);

        lblName2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblName2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName2.setText("Enterprise:");

        entrpiseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrpiseComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName1)
                            .addComponent(lblName2)
                            .addComponent(lblGender))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveOrg)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateOrg)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelOrg))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(entrpiseComboBox, 0, 250, Short.MAX_VALUE)
                                    .addComponent(txtOrgName)
                                    .addComponent(orgTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(123, 123, 123)
                                .addComponent(btnViewOrg)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteOrg)))
                        .addGap(24, 24, 24)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel73)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDeleteOrg)
                                .addComponent(btnViewOrg))
                            .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orgTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entrpiseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName2)))
                    .addComponent(lblName1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveOrg)
                    .addComponent(btnUpdateOrg)
                    .addComponent(btnCancelOrg))
                .addContainerGap(298, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrgActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = OrgTbl.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }
        
        // Validation if any field is left empty
        if(txtOrgName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the fields");
            return;
        }  
        
        DefaultTableModel model = (DefaultTableModel) OrgTbl.getModel();
        Organization selectedOrgDetails = (Organization) model.getValueAt(selectedRowIndex, 0);
        Enterprise selectedEnterpriseDetails = (Enterprise) model.getValueAt(selectedRowIndex, 2);
        
        String orgName = txtOrgName.getText();
        selectedOrgDetails.setName(orgName);
        
        String entName = (String) entrpiseComboBox.getSelectedItem();
        Enterprise selectedEnterprise = system.findEnterpriseByName(entName);
        system.updateOrganizationEnterpriseLink(selectedOrgDetails, selectedEnterprise);
        
        Type orgType = getOrganizationType((String) orgTypeComboBox.getSelectedItem());
        selectedOrgDetails.setType(orgType);

        populateOrgTable();
        clearOrgFields();
        JOptionPane.showMessageDialog(this, "Organization Information Updated");
    }//GEN-LAST:event_btnUpdateOrgActionPerformed

    private void btnCancelOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrgActionPerformed
        // TODO add your handling code here:
        clearOrgFields();
    }//GEN-LAST:event_btnCancelOrgActionPerformed

    private void btnSaveOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveOrgActionPerformed
        // TODO add your handling code here:
        // Validation if any field is left empty
        String entName = (String) entrpiseComboBox.getSelectedItem();
        Enterprise selectedEnterprise = system.findEnterpriseByName(entName);
        
        // Validation if any field is left empty
        if(txtOrgName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the fields");
            return;
        }        
        
        String orgName = txtOrgName.getText();
        Type otgType = getOrganizationType((String) orgTypeComboBox.getSelectedItem());
        Organization newOrganization = selectedEnterprise.getOrganizationDir().createOrganization(orgName, otgType);
        system.addOrganizationEnterprise(newOrganization, selectedEnterprise);
        JOptionPane.showMessageDialog(this, "Organization Saved");
        populateOrgTable();
        clearOrgFields();
    }//GEN-LAST:event_btnSaveOrgActionPerformed

    private void btnViewOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrgActionPerformed
        // TODO add your handling code here:
        btnUpdateOrg.setEnabled(true);
        btnSaveOrg.setEnabled(false);

        int selectedRowIndex = OrgTbl.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a Row to View.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) OrgTbl.getModel();
        Organization selectedOrgDetails = (Organization) model.getValueAt(selectedRowIndex, 0);
        Enterprise selectedEnterpriseDetails = (Enterprise) model.getValueAt(selectedRowIndex, 2);

        txtOrgName.setText(selectedOrgDetails.getName());
        entrpiseComboBox.setSelectedItem(selectedEnterpriseDetails.getName());
        orgTypeComboBox.setSelectedItem(convertOrganizationToDisplayName(selectedOrgDetails.getType()));

    }//GEN-LAST:event_btnViewOrgActionPerformed

    private void btnDeleteOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrgActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = OrgTbl.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a Row to View.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) OrgTbl.getModel();
        Organization selectedOrgDetails = (Organization) model.getValueAt(selectedRowIndex, 0);

        // Show a warning dialog with Yes/No options
        int userChoice = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete?",
                "Warning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // Check the user's choice
        if (userChoice == JOptionPane.YES_OPTION) {
            system.deleteOrganization(selectedOrgDetails);
            populateOrgTable();
        }
    }//GEN-LAST:event_btnDeleteOrgActionPerformed

    private void orgTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgTypeComboBoxActionPerformed

    private void entrpiseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrpiseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrpiseComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrgTbl;
    private javax.swing.JButton btnCancelOrg;
    private javax.swing.JButton btnDeleteOrg;
    private javax.swing.JButton btnSaveOrg;
    private javax.swing.JButton btnUpdateOrg;
    private javax.swing.JButton btnViewOrg;
    private javax.swing.JComboBox<String> entrpiseComboBox;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JComboBox<String> orgTypeComboBox;
    private javax.swing.JTextField txtOrgName;
    // End of variables declaration//GEN-END:variables
}
