/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.marketPlace;

import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.organization.MarketplaceOrg;
import edu.neu.wasteManagement.business.organization.Organization;
import edu.neu.wasteManagement.business.products.Order;
import edu.neu.wasteManagement.business.products.Product;
import edu.neu.wasteManagement.business.products.ProductCatalog;
import edu.neu.wasteManagement.ui.BaseJPanel;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author prart
 */
public class ViewBuyOrdersNewJPanel extends BaseJPanel {

    private MarketplaceOrg marketplace;

    /**
     * Creates new form ViewBuyOrdersNewJPanel
     */
    public ViewBuyOrdersNewJPanel(Ecosystem system) {
        super(system);
        initComponents();
        String marketplaceOrgName = "Marketplace Organization";
        Organization marketplaceOrg = system.findOrganizationByName(marketplaceOrgName);

        if (marketplaceOrg instanceof MarketplaceOrg) {
            marketplace = (MarketplaceOrg) marketplaceOrg;
            populateUserOrdersTable();
        } else {
            System.out.println("The organization is not of type MarketplaceOrg");
        }
    }

    public List<Product> getAllProducts() {
        List<Product> allProducts = new ArrayList<>();

        if (marketplace != null) {
            ProductCatalog catalog = marketplace.getCatalog();
            allProducts = catalog.getProducts();
        }

        return allProducts;
    }

    public void populateUserOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) UserOrdersTable.getModel();
        JTableHeader header = UserOrdersTable.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 14));
        model.setRowCount(0);
        ProductCatalog catalog = marketplace.getCatalog();
        List<Order> userOrders = catalog.getOrdersByUsername(system.getLoggedInUser().getUsername());
        for (Order order : userOrders) {
            Object[] row = new Object[5];
            row[0] = order.getProduct();
            row[1] = order.getProduct().getPrice();
            row[2] = order.getQuantity();
            row[3] = order.getFinalPrice();
            row[4] = order.getSeller();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UserOrdersTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        UserOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Price", "Quanity", "Total Price", "Seller"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserOrdersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserOrdersTableMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserOrdersTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(UserOrdersTable);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("My Orders");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UserOrdersTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserOrdersTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_UserOrdersTableMouseEntered

    private void UserOrdersTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserOrdersTableMousePressed
        // TODO add your handling code here:
        int suppliertablesize = UserOrdersTable.getRowCount();
        int selectedrow = UserOrdersTable.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > suppliertablesize - 1) {
            return;
        }
    }//GEN-LAST:event_UserOrdersTableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserOrdersTable;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
