/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.wasteManagement.ui.cordinator;

import edu.neu.wasteManagement.ui.integrator.*;
import edu.neu.wasteManagement.ui.common.*;
import edu.neu.wasteManagement.business.Ecosystem;
import edu.neu.wasteManagement.business.organization.MarketplaceOrg;
import edu.neu.wasteManagement.business.organization.Organization;
import edu.neu.wasteManagement.business.organization.Type;
import edu.neu.wasteManagement.business.products.Product;
import edu.neu.wasteManagement.business.products.Product.ProductType;
import edu.neu.wasteManagement.business.products.ProductCatalog;
import edu.neu.wasteManagement.business.userAccount.UserAccount;
import edu.neu.wasteManagement.business.workQueue.UserWasteCollectionRequest;
import edu.neu.wasteManagement.business.workQueue.Waste;
import edu.neu.wasteManagement.business.workQueue.WasteProcessingRequest;
import edu.neu.wasteManagement.business.workQueue.WorkRequest;
import edu.neu.wasteManagement.business.workQueue.WorkRequestType;
import edu.neu.wasteManagement.ui.BaseJPanel;
import edu.neu.wasteManagement.utility.Utility;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ingale.r
 */
public class PerformancesIndices extends BaseJPanel {

    /**
     * Creates new form CreateCourseJPanel
     */

    private List<Waste> wastes;
    private List<WorkRequest> requests;
    private List<Product> products;
    public PerformancesIndices(Ecosystem system) {
        super(system);
        this.wastes = new ArrayList<>();
        this.requests = new ArrayList<>();
        this.products = new ArrayList<>();
        initComponents();
        initSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerformances = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTopCourses = new javax.swing.JButton();
        btnTopProfessors = new javax.swing.JButton();
        btnTopStudents = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblPerformances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPerformances.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPerformancesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblPerformancesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPerformances);

        jLabel1.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Top Performances");

        btnTopCourses.setBackground(new java.awt.Color(105, 155, 247));
        btnTopCourses.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnTopCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnTopCourses.setText("Top Organization Trash Processed");
        btnTopCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopCoursesMouseClicked(evt);
            }
        });
        btnTopCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopCoursesActionPerformed(evt);
            }
        });

        btnTopProfessors.setBackground(new java.awt.Color(105, 155, 247));
        btnTopProfessors.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnTopProfessors.setForeground(new java.awt.Color(255, 255, 255));
        btnTopProfessors.setText("Top Organization Trash Generated");
        btnTopProfessors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopProfessorsMouseClicked(evt);
            }
        });
        btnTopProfessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopProfessorsActionPerformed(evt);
            }
        });

        btnTopStudents.setBackground(new java.awt.Color(105, 155, 247));
        btnTopStudents.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnTopStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnTopStudents.setText("Top 3 User Trash ");
        btnTopStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopStudentsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTopStudentsMousePressed(evt);
            }
        });
        btnTopStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopStudentsActionPerformed(evt);
            }
        });
        btnTopStudents.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTopStudentsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTopStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTopProfessors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTopCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel1)))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnTopStudents)
                        .addGap(39, 39, 39)
                        .addComponent(btnTopProfessors)
                        .addGap(53, 53, 53)
                        .addComponent(btnTopCourses)))
                .addContainerGap(780, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPerformancesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPerformancesKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblPerformancesKeyPressed

    private void tblPerformancesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPerformancesKeyReleased

    }//GEN-LAST:event_tblPerformancesKeyReleased

    private void btnTopCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopCoursesMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTopCoursesMouseClicked

    private void btnTopCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopCoursesActionPerformed
        // TODO add your handling code here:
        populateTopTrashProcessed();
    }//GEN-LAST:event_btnTopCoursesActionPerformed

    private void btnTopProfessorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopProfessorsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTopProfessorsMouseClicked

    private void btnTopProfessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopProfessorsActionPerformed
        // TODO add your handling code here:
        populateOrgTrashGenerated();
    }//GEN-LAST:event_btnTopProfessorsActionPerformed

    private void btnTopStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopStudentsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTopStudentsMouseClicked

    private void btnTopStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopStudentsActionPerformed
        // TODO add your handling code here:
       populateTop3UserTrash();

    }//GEN-LAST:event_btnTopStudentsActionPerformed

    private void btnTopStudentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTopStudentsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopStudentsKeyPressed

    private void btnTopStudentsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopStudentsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopStudentsMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTopCourses;
    private javax.swing.JButton btnTopProfessors;
    private javax.swing.JButton btnTopStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerformances;
    // End of variables declaration//GEN-END:variables

    private void initSetup() {
       
       populateTop3UserTrash();
    }
    
 
   

    private void populateTop3UserTrash() {
        DefaultTableModel model = (DefaultTableModel) tblPerformances.getModel();
        model.setRowCount(0);

        List<UserAccount> topUsers = system.Top3UserTrash(); // Assuming you have a method to get the top professors

        for (UserAccount user : topUsers) {
            Object[] row = new Object[2];
            row[0] = user;
            row[1] = user.getTotalTrash();
            model.addRow(row);
        }
    }

    private void populateOrgTrashGenerated() {
        DefaultTableModel model = (DefaultTableModel) tblPerformances.getModel();
        model.setRowCount(0);

        List<Organization> topOrg = system.Top3OrgTrashGenerated(); // Assuming you have a method to get the top professors

        for (Organization org : topOrg) {
            Object[] row = new Object[2];
            row[0] = org;
            row[1] = org.getTrashGenerated();
            model.addRow(row);
        }
    }

    private void populateTopTrashProcessed() {

    }


}


